<?php

namespace Yoda\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{

    //Anything written in here gets precedence over the EntityRepository base class
//    public function findAll()
//    {
//
//        die( 'NOOOOO!' );
//
//    }

}
